-- Active: 1714132218367@@127.0.0.1@5432@final_project@public
-- Insert dummy data into airlines
INSERT INTO public.airlines ("airlineCode", "airlineName", image, "createdAt", "updatedAt") VALUES
('AA', 'American Airlines', 'image_aa.png', NOW(), NOW()),
('DL', 'Delta Airlines', 'image_dl.png', NOW(), NOW()),
('UA', 'United Airlines', 'image_ua.png', NOW(), NOW());

-- Insert dummy data into airports
INSERT INTO public.airports ("airportCode", "airportName", city, country, "createdAt", "updatedAt") VALUES
('JFK', 'John F. Kennedy International Airport', 'New York', 'USA', NOW(), NOW()),
('LAX', 'Los Angeles International Airport', 'Los Angeles', 'USA', NOW(), NOW()),
('ORD', 'Hare International Airport', 'Chicago', 'USA', NOW(), NOW());

-- Insert dummy data into users
-- password1
INSERT INTO public.users (name, email, password, image, "phoneNumber", "isVerified", "createdAt", "updatedAt") VALUES
('John Doe', 'john.doe@example.com', '$2a$10$knQwGRHcSvEPJD41Sgu1hOsyBobQZzPihmbokdLbngAtWhyUfPYvm', 'image_john.png', '123-456-7890', true, NOW(), NOW()),
-- password2
('Jane Smith', 'jane.smith@example.com', '$2a$10$EkPP1d8a6XQLtCLXv7nNN.OFcdC8g9pCbIl8GXT1dQ4ovpAgzUumi', 'image_jane.png', '987-654-3210', true, NOW(), NOW()),
-- password3
('Alice Johnson', 'alice.johnson@example.com', '$2a$10$no5I2daewdVoVE5YoZlC5u/u41u2jnUwlDWz8HKctgtG3vNUk1HS6', 'image_alice.png', '456-789-0123', false, NOW(), NOW());

-- Insert dummy data into flights
INSERT INTO public.flights ("flightCode", terminal, "departureAirportId", "arrivalAirportId", "airlineId", "price", "departureTime", "arrivalTime", information, "createdAt", "updatedAt") VALUES
('AA100', 'T1', 1, 2, 1, 750000, '2024-06-01 08:00:00+00', '2024-06-01 11:00:00+00', 'Non-stop', NOW(), NOW()),
('DL200', 'T2', 2, 3, 2, 850000, '2024-06-02 09:00:00+00', '2024-06-02 12:00:00+00', 'Non-stop', NOW(), NOW()),
('UA300', 'T3', 3, 1, 3, 950000, '2024-06-03 10:00:00+00', '2024-06-03 13:00:00+00', 'Non-stop', NOW(), NOW());

-- Insert dummy data into bookings
INSERT INTO public.bookings ("bookingCode", "departureFlightId", "returnFlightId", "userId", "numAdults", "numChildren", "numBabies", "createdAt", "updatedAt") VALUES
('BK001', 1, 2, 1, 2, 1, 0, NOW(), NOW()),
('BK002', 2, 1, 2, 1, 0, 1, NOW(), NOW()),
('BK003', 3, 1, 3, 1, 1, 1, NOW(), NOW());

-- Insert dummy data into passengers
INSERT INTO public.passengers (name, "dateOfBirth", nationality, "docType", "docNumber", "issuingCountry", "expiryDate", "passengerType", "createdAt", "updatedAt") VALUES
('John Doe Jr.', '2010-01-01 00:00:00+00', 'USA', 'paspor', 'P123456', 'USA', '2030-01-01 00:00:00+00', 'adult', NOW(), NOW()),
('Jane Smith Jr.', '2015-01-01 00:00:00+00', 'USA', 'paspor', 'P654321', 'USA', '2035-01-01 00:00:00+00', 'baby', NOW(), NOW()),
('Alice Johnson Jr.', '2012-01-01 00:00:00+00', 'USA', 'paspor', 'P112233', 'USA', '2032-01-01 00:00:00+00', 'children', NOW(), NOW());

-- Insert dummy data into seats
-- For Flight ID 1
INSERT INTO public.seats ("seatCode", "seatAvailable", "flightId", "createdAt", "updatedAt") VALUES
('1A', true, 1, NOW(), NOW()),
('1B', true, 1, NOW(), NOW()),
('1C', true, 1, NOW(), NOW()),
('1D', true, 1, NOW(), NOW()),
('1E', true, 1, NOW(), NOW()),
('1F', true, 1, NOW(), NOW()),
('2A', true, 1, NOW(), NOW()),
('2B', true, 1, NOW(), NOW()),
('2C', true, 1, NOW(), NOW()),
('2D', true, 1, NOW(), NOW()),
('2E', true, 1, NOW(), NOW()),
('2F', true, 1, NOW(), NOW()),
('3A', true, 1, NOW(), NOW()),
('3B', true, 1, NOW(), NOW()),
('3C', true, 1, NOW(), NOW()),
('3D', true, 1, NOW(), NOW()),
('3E', true, 1, NOW(), NOW()),
('3F', true, 1, NOW(), NOW()),
('4A', true, 1, NOW(), NOW()),
('4B', true, 1, NOW(), NOW()),
('4C', true, 1, NOW(), NOW()),
('4D', true, 1, NOW(), NOW()),
('4E', true, 1, NOW(), NOW()),
('4F', true, 1, NOW(), NOW()),
('5A', true, 1, NOW(), NOW()),
('5B', true, 1, NOW(), NOW()),
('5C', true, 1, NOW(), NOW()),
('5D', true, 1, NOW(), NOW()),
('5E', true, 1, NOW(), NOW()),
('5F', true, 1, NOW(), NOW()),
('6A', true, 1, NOW(), NOW()),
('6B', true, 1, NOW(), NOW()),
('6C', true, 1, NOW(), NOW()),
('6D', true, 1, NOW(), NOW()),
('6E', true, 1, NOW(), NOW()),
('6F', true, 1, NOW(), NOW()),
('7A', true, 1, NOW(), NOW()),
('7B', true, 1, NOW(), NOW()),
('7C', true, 1, NOW(), NOW()),
('7D', true, 1, NOW(), NOW()),
('7E', true, 1, NOW(), NOW()),
('7F', true, 1, NOW(), NOW()),
('8A', true, 1, NOW(), NOW()),
('8B', true, 1, NOW(), NOW()),
('8C', true, 1, NOW(), NOW()),
('8D', true, 1, NOW(), NOW()),
('8E', true, 1, NOW(), NOW()),
('8F', true, 1, NOW(), NOW()),
('9A', true, 1, NOW(), NOW()),
('9B', true, 1, NOW(), NOW()),
('9C', true, 1, NOW(), NOW()),
('9D', true, 1, NOW(), NOW()),
('9E', true, 1, NOW(), NOW()),
('9F', true, 1, NOW(), NOW()),
('10A', true, 1, NOW(), NOW()),
('10B', true, 1, NOW(), NOW()),
('10C', true, 1, NOW(), NOW()),
('10D', true, 1, NOW(), NOW()),
('10E', true, 1, NOW(), NOW()),
('10F', true, 1, NOW(), NOW()),
('11A', true, 1, NOW(), NOW()),
('11B', true, 1, NOW(), NOW()),
('11C', true, 1, NOW(), NOW()),
('11D', true, 1, NOW(), NOW()),
('11E', true, 1, NOW(), NOW()),
('11F', true, 1, NOW(), NOW()),
('12A', true, 1, NOW(), NOW()),
('12B', true, 1, NOW(), NOW()),
('12C', true, 1, NOW(), NOW()),
('12D', true, 1, NOW(), NOW()),
('12E', true, 1, NOW(), NOW()),
('12F', true, 1, NOW(), NOW());

-- For Flight ID 2
INSERT INTO public.seats ("seatCode", "seatAvailable", "flightId", "createdAt", "updatedAt") VALUES
('1A', true, 2, NOW(), NOW()),
('1B', true, 2, NOW(), NOW()),
('1C', true, 2, NOW(), NOW()),
('1D', true, 2, NOW(), NOW()),
('1E', true, 2, NOW(), NOW()),
('1F', true, 2, NOW(), NOW()),
('2A', true, 2, NOW(), NOW()),
('2B', true, 2, NOW(), NOW()),
('2C', true, 2, NOW(), NOW()),
('2D', true, 2, NOW(), NOW()),
('2E', true, 2, NOW(), NOW()),
('2F', true, 2, NOW(), NOW()),
('3A', true, 2, NOW(), NOW()),
('3B', true, 2, NOW(), NOW()),
('3C', true, 2, NOW(), NOW()),
('3D', true, 2, NOW(), NOW()),
('3E', true, 2, NOW(), NOW()),
('3F', true, 2, NOW(), NOW()),
('4A', true, 2, NOW(), NOW()),
('4B', true, 2, NOW(), NOW()),
('4C', true, 2, NOW(), NOW()),
('4D', true, 2, NOW(), NOW()),
('4E', true, 2, NOW(), NOW()),
('4F', true, 2, NOW(), NOW()),
('5A', true, 2, NOW(), NOW()),
('5B', true, 2, NOW(), NOW()),
('5C', true, 2, NOW(), NOW()),
('5D', true, 2, NOW(), NOW()),
('5E', true, 2, NOW(), NOW()),
('5F', true, 2, NOW(), NOW()),
('6A', true, 2, NOW(), NOW()),
('6B', true, 2, NOW(), NOW()),
('6C', true, 2, NOW(), NOW()),
('6D', true, 2, NOW(), NOW()),
('6E', true, 2, NOW(), NOW()),
('6F', true, 2, NOW(), NOW()),
('7A', true, 2, NOW(), NOW()),
('7B', true, 2, NOW(), NOW()),
('7C', true, 2, NOW(), NOW()),
('7D', true, 2, NOW(), NOW()),
('7E', true, 2, NOW(), NOW()),
('7F', true, 2, NOW(), NOW()),
('8A', true, 2, NOW(), NOW()),
('8B', true, 2, NOW(), NOW()),
('8C', true, 2, NOW(), NOW()),
('8D', true, 2, NOW(), NOW()),
('8E', true, 2, NOW(), NOW()),
('8F', true, 2, NOW(), NOW()),
('9A', true, 2, NOW(), NOW()),
('9B', true, 2, NOW(), NOW()),
('9C', true, 2, NOW(), NOW()),
('9D', true, 2, NOW(), NOW()),
('9E', true, 2, NOW(), NOW()),
('9F', true, 2, NOW(), NOW()),
('10A', true, 2, NOW(), NOW()),
('10B', true, 2, NOW(), NOW()),
('10C', true, 2, NOW(), NOW()),
('10D', true, 2, NOW(), NOW()),
('10E', true, 2, NOW(), NOW()),
('10F', true, 2, NOW(), NOW()),
('11A', true, 2, NOW(), NOW()),
('11B', true, 2, NOW(), NOW()),
('11C', true, 2, NOW(), NOW()),
('11D', true, 2, NOW(), NOW()),
('11E', true, 2, NOW(), NOW()),
('11F', true, 2, NOW(), NOW()),
('12A', true, 2, NOW(), NOW()),
('12B', true, 2, NOW(), NOW()),
('12C', true, 2, NOW(), NOW()),
('12D', true, 2, NOW(), NOW()),
('12E', true, 2, NOW(), NOW()),
('12F', true, 2, NOW(), NOW());

-- For Flight ID 3
INSERT INTO public.seats ("seatCode", "seatAvailable", "flightId", "createdAt", "updatedAt") VALUES
('1A', true, 3, NOW(), NOW()),
('1B', true, 3, NOW(), NOW()),
('1C', true, 3, NOW(), NOW()),
('1D', true, 3, NOW(), NOW()),
('1E', true, 3, NOW(), NOW()),
('1F', true, 3, NOW(), NOW()),
('2A', true, 3, NOW(), NOW()),
('2B', true, 3, NOW(), NOW()),
('2C', true, 3, NOW(), NOW()),
('2D', true, 3, NOW(), NOW()),
('2E', true, 3, NOW(), NOW()),
('2F', true, 3, NOW(), NOW()),
('3A', true, 3, NOW(), NOW()),
('3B', true, 3, NOW(), NOW()),
('3C', true, 3, NOW(), NOW()),
('3D', true, 3, NOW(), NOW()),
('3E', true, 3, NOW(), NOW()),
('3F', true, 3, NOW(), NOW()),
('4A', true, 3, NOW(), NOW()),
('4B', true, 3, NOW(), NOW()),
('4C', true, 3, NOW(), NOW()),
('4D', true, 3, NOW(), NOW()),
('4E', true, 3, NOW(), NOW()),
('4F', true, 3, NOW(), NOW()),
('5A', true, 3, NOW(), NOW()),
('5B', true, 3, NOW(), NOW()),
('5C', true, 3, NOW(), NOW()),
('5D', true, 3, NOW(), NOW()),
('5E', true, 3, NOW(), NOW()),
('5F', true, 3, NOW(), NOW()),
('6A', true, 3, NOW(), NOW()),
('6B', true, 3, NOW(), NOW()),
('6C', true, 3, NOW(), NOW()),
('6D', true, 3, NOW(), NOW()),
('6E', true, 3, NOW(), NOW()),
('6F', true, 3, NOW(), NOW()),
('7A', true, 3, NOW(), NOW()),
('7B', true, 3, NOW(), NOW()),
('7C', true, 3, NOW(), NOW()),
('7D', true, 3, NOW(), NOW()),
('7E', true, 3, NOW(), NOW()),
('7F', true, 3, NOW(), NOW()),
('8A', true, 3, NOW(), NOW()),
('8B', true, 3, NOW(), NOW()),
('8C', true, 3, NOW(), NOW()),
('8D', true, 3, NOW(), NOW()),
('8E', true, 3, NOW(), NOW()),
('8F', true, 3, NOW(), NOW()),
('9A', true, 3, NOW(), NOW()),
('9B', true, 3, NOW(), NOW()),
('9C', true, 3, NOW(), NOW()),
('9D', true, 3, NOW(), NOW()),
('9E', true, 3, NOW(), NOW()),
('9F', true, 3, NOW(), NOW()),
('10A', true, 3, NOW(), NOW()),
('10B', true, 3, NOW(), NOW()),
('10C', true, 3, NOW(), NOW()),
('10D', true, 3, NOW(), NOW()),
('10E', true, 3, NOW(), NOW()),
('10F', true, 3, NOW(), NOW()),
('11A', true, 3, NOW(), NOW()),
('11B', true, 3, NOW(), NOW()),
('11C', true, 3, NOW(), NOW()),
('11D', true, 3, NOW(), NOW()),
('11E', true, 3, NOW(), NOW()),
('11F', true, 3, NOW(), NOW()),
('12A', true, 3, NOW(), NOW()),
('12B', true, 3, NOW(), NOW()),
('12C', true, 3, NOW(), NOW()),
('12D', true, 3, NOW(), NOW()),
('12E', true, 3, NOW(), NOW()),
('12F', true, 3, NOW(), NOW());



-- Insert dummy data into booking_details
INSERT INTO public.booking_details ("bookingId", "passengerId", "seatId", "createdAt", "updatedAt") VALUES
(1, 1, 1, NOW(), NOW()),
(2, 2, 2, NOW(), NOW()),
(3, 3, 3, NOW(), NOW());

-- Insert dummy data into payments
INSERT INTO public.payments ("bookingId", "paymentAmount", "paymentMethod", "paymentStatus", "createdAt", "updatedAt") VALUES
(1, 400, 'credit card', 'paid', NOW(), NOW()),
(2, 200, 'paypal', 'paid', NOW(), NOW()),
(3, 600, 'credit card', 'pending', NOW(), NOW());